name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ali Erdem Akın
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: vue,makefile,css,html,scss,brainfuck,javascript
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
